name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  main:
    permissions:
      pull-requests: read # for amannn/action-semantic-pull-request to analyze PRs
      statuses: write # for amannn/action-semantic-pull-request to mark status of analyzed PR
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.2.0
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true

  check-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: check for breaking proto changes
        run: make proto-check-breaking      
      - name: check proto formatting
        run: |
          make proto-format
          if [[ `git status --porcelain` ]]; then
            echo "Proto files are not formatted. Please run `make proto-format`"
            exit 1
          fi
      - name: lint protos
        run: make proto-lint   
      - name: check generated protos
        run: |
          make proto-gen
          if [[ `git status --porcelain` ]]; then
            echo "Proto files are not up to date. Please run `make proto-gen`"
            exit 1
          fi
      - name: check generated dependency injection protos
        run: |
          make proto-pulsar-gen
          if [[ `git status --porcelain` ]]; then
            echo "Proto files for dependency injection are not up to date. Please run `make proto-pulsar-gen`"
            exit 1
          fi
